"""Initial migration

Revision ID: 779f50b2c3a3
Revises: 
Create Date: 2025-09-20 11:28:49.263229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779f50b2c3a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
