"""Added OTP fields to User

Revision ID: 822e3a1930e5
Revises: 404ff7c61e49
Create Date: 2026-04-04 11:23:36.635344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822e3a1930e5'
down_revision = '404ff7c61e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vet_appointment', schema=None) as batch_op:
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_appointment', schema=None) as batch_op:
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
