"""Add supplier_id to OrderItem

Revision ID: 9b3b2d525826
Revises: 779f50b2c3a3
Create Date: 2025-09-20 12:01:00.197415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3b2d525826'
down_revision = '779f50b2c3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_orderitem_supplier_id',   # constraint name
            'user',                       # target table
            ['supplier_id'],              # local column
            ['id']                        # remote column
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orderitem_supplier_id', type_='foreignkey')
        batch_op.drop_column('supplier_id')
    # ### end Alembic commands ###
