"""Added image to VetAppointmentSlot

Revision ID: 9f9c21ff1200
Revises: 2d5957d8266c
Create Date: 2026-02-17 12:34:05.249720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9c21ff1200'
down_revision = '2d5957d8266c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_appointment_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_appointment_slot', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
