"""Added VetAppointment

Revision ID: fadca9ebe37a
Revises: 9f9c21ff1200
Create Date: 2026-02-17 12:56:29.940096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadca9ebe37a'
down_revision = '9f9c21ff1200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vet_appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('pet_owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['vet_appointment_slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vet_appointment')
    # ### end Alembic commands ###
